substitutions:
  _REGION: "europe-west1"
  _REPO: "portfolio-repo"
  _IMAGE: "portfolio-app"
  _SERVICE: "portfolio"
  _PROJECT: "fintech-inv-recomm"

steps:
  # Clean rebuild: no cache to ensure no stale code
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--no-cache",
        "--pull",
        "--build-arg","GIT_SHA=$SHORT_SHA",
        "-t","${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/${_IMAGE}:$SHORT_SHA",
        "-t","${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/${_IMAGE}:latest",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push","${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/${_IMAGE}:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push","${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/${_IMAGE}:latest"]

  # Deploy with a unique revision suffix; retry if there's a version conflict
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -lc
      - |
        set -e
        for i in 1 2 3; do
          gcloud run deploy "${_SERVICE}" \
            --image "${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/${_IMAGE}:$SHORT_SHA" \
            --region "${_REGION}" \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --memory 512Mi \
            --cpu 1 \
            --concurrency 80 \
            --revision-suffix "$SHORT_SHA" \
            --quiet && break
          echo "Deploy conflict, retrying in 6s (attempt $i/3)…"
          sleep 6
        done

images:
  - "${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/${_IMAGE}:$SHORT_SHA"
  - "${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/${_IMAGE}:latest"

options:
  logging: CLOUD_LOGGING_ONLY
